language: python
python: 3.6

install: 
  - ':'

script: 
  - ':'

after_script:
  - git config user.name ${GH_UN}
  - git config user.email ${GH_EMAIL}
  - git push "https://${GH_TOKEN}@github.com/${GH_USER}/${GH_REPO}.git" v0.19.x-md:${GH_BRANCH} -f
  
env:
  global:
    - GH_UN=jiangzhonglian
    - GH_EMAIL=jiang-s@163.com
    - GH_USER=apachecn
    - GH_REPO=scikit-learn-doc-zh
    - GH_BRANCH=gh-pages